const ADD_USER = "ADD_USER";
const ADD_USER_ERROR = "ADD_USER_ERROR";
const ADD_INTERVIEW_LIST = "ADD_INTERVIEW_LIST";
const ADD_CURRENT_INTREVIEW = "ADD_CURRENT_INTREVIEW";
const ADD_FEEDBACK = "ADD_FEEDBACK";
const PUT_FEEDBACK = "PUT_FEEDBACK";
const FEEDBACK_UPLOADED = "FEEDBACK_UPLOADED";

// auth
export { ADD_USER };
export { ADD_USER_ERROR };
// interviews
export { ADD_INTERVIEW_LIST };
export { ADD_CURRENT_INTREVIEW };
export { ADD_FEEDBACK };
export { FEEDBACK_UPLOADED };
